services:
  attacker3:
    container_name: attacker3
    build:
      context: ../../
      dockerfile: nodes/attacker3/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./MASTER_CONFIG.json:/MASTER_CONFIG.json
  attacker3_node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: attacker3_node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=0.0.0.0:9100'
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'