global:
  scrape_interval: 3s
scrape_configs:
  - job_name: 'nodes'
    static_configs:
      - targets: ['target1:8000']
        labels:
          node: 'target1'
      - targets: ['attacker1:8000']
        labels:
          node: 'attacker1'
      - targets: ['attacker1-john:8000']
        labels:
          node: 'attacker1-john'
      - targets: ['attacker2:8000']
        labels:
          node: 'attacker2'
      - targets: ['attacker3:8000']
        labels:
          node: 'attacker3'
      - targets: ['nginx-exporter:9113']
        labels:
          node: "proxy"
      - targets: ['proxy-fastapi:8000']
        labels:
          node: "proxy-fastapi"
      - targets: ['docker-exporter:9487']
        labels:
          node: "docker-exporter"