version: "3.9"

services:
  upstream:
    image: python:3.11-slim
    container_name: upstream_nginx
    command: ["python", "-m", "http.server", "9000", "--bind", "0.0.0.0"]
    expose:
      - "9000"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_proxy
    ports:
      - "8001:8000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - upstream
    networks:
      - ddos-shared

networks:
  ddos-shared:
    external: True