services:
  attacker:
    container_name: attacker2
    build: 
      context: ../../
      dockerfile: nodes/attacker2/Dockerfile
    ports:
      - "8000:8000"
    volumes: 
      - ./app:/app
    networks: 
      - ddos-shared
    
networks:
  ddos-shared:
    external: true
