services:
  attacker2:
    container_name: attacker2
    build: 
      context: ../../
      dockerfile: nodes/attacker2/Dockerfile.pi
    ports:
      - "8000:8000"
    volumes: 
      - ./app:/app
      - ./control:/control # Pass through for systemd service
      - ./MASTER_CONFIG.json:/MASTER_CONFIG.json  # Config (restart to reload)
  attaker2_node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: attacker2_node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=0.0.0.0:9100'
    network_mode: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'