services:
  attacker2:
    container_name: attacker2
    build: 
      context: ../../
      dockerfile: nodes/attacker2/Dockerfile
    ports:
      - "8002:8000"
    volumes: 
      - ./app:/app
      - ./control:/control # Pass through for systemd service
      - ./MASTER_CONFIG.json:/MASTER_CONFIG.json  # Config (restart to reload)
    cpuset: "1,2"
    mem_limit: 2g
    networks: 
      - ddos-shared
  
  # attacker2_node_exporter:
  #   image: quay.io/prometheus/node-exporter:latest
  #   container_name: attacker2_node_exporter
  #   command:
  #     # - '--path.rootfs=/host'
  #     - '--web.listen-address=0.0.0.0:9100'
  #     - '--path.procfs=/host/proc'
  #     - '--path.sysfs=/host/sys'
  #   ports:
  #     - "9100:9100"
  #   restart: unless-stopped
  #   volumes:
  #     # - '/:/host:ro,rslave'
  #     - /proc:/host/proc:ro
  #     - /sys:/host/sys:ro
    
networks:
  ddos-shared:
    external: true
