services:
  attacker1-john:
    container_name: attacker1-john
    build: 
      context: ../../
      dockerfile: nodes/attacker1-john/Dockerfile
    ports:
      - "8010:8000"
    volumes: 
      - ./app:/app
      - ./control:/control # Pass through for systemd service
    networks: 
      - ddos-shared
    
networks:
  ddos-shared:
    external: true
