# version: '3'
# services:
#   prometheus:
#     image: prom/prometheus
#     ports:
#       - '9090:9090'
#     volumes:
#       - ./prometheus:/etc/prometheus
#     command:
#       - '--config.file=/etc/prometheus/prometheus.yml'
#     restart: always
    
#     networks:
#       - ddos-shared
#   grafana:
#     image: grafana/grafana
#     logging:
#       driver: none
#     ports:
#       - '3000:3000'
#     depends_on:
#       - prometheus
#     command:
#       - ''
#     restart: always
#     networks:
#       - ddos-shared

# networks:
#   ddos-shared:
#     external: True

version: "3.8"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always
    cpuset: "7"
    mem_limit: 2g
    networks:
      - ddos-shared

  grafana:
    image: grafana/grafana
    container_name: grafana
    cpuset: "7"
    mem_limit: 2g
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    logging:
      driver: none
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ~/grafana-data:/var/lib/grafana
    restart: always
    networks:
      - ddos-shared

networks:
  ddos-shared:
    external: true

