global:
  scrape_interval: 3s
scrape_configs:
  - job_name: 'nodes'
    static_configs:
      - targets: ['192.168.192.205:8000']
        labels:
          node: 'target1'
      - targets: ['192.168.192.201:8000']
        labels:
          node: 'attacker1'
      - targets: ['192.168.192.202:8000']
        labels:
          node: 'attacker2'
      - targets: ['192.168.192.203:8000']
        labels:
          node: 'attacker3'
      - targets: ['192.168.192.204:9113']
        labels:
          node: "proxy"
      - targets: ['192.168.192.204:8000']
        labels:
          node: "proxy-fastapi"