services:
  target1:
    build:
      context: ../../
      dockerfile: nodes/target1/Dockerfile
    container_name: target1
    ports:
      - "8002:8000"
    volumes:
      - ./app:/app/app
      - ./MASTER_CONFIG.json:/app/MASTER_CONFIG.json
    cpuset: "6,7"
    mem_limit: 2g
    networks:
      - ddos-shared

networks:
  ddos-shared:
    external: True
