services:
  target1:
    build:
      context: ../../
      dockerfile: nodes/target1/Dockerfile
    container_name: target1
    ports:
      - "8002:8000"
    networks:
      - ddos-shared

networks:
  ddos-shared:
    external: True
