services:
  target1:
    build:
      context: ../../
      dockerfile: nodes/target1/Dockerfile
    container_name: target1
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./MASTER_CONFIG.json:/app/MASTER_CONFIG.json
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: target1_node_exporter
    command:
      - '--path.rootfs=/host'
      - '--web.listen-address=0.0.0.0:9100'
    # network_mode: host
    # pid: host
    ports:
      - "9100:9100"
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'