services:
  target1:
    build:
      context: ../../
      dockerfile: nodes/target1/Dockerfile
    container_name: target1
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./MASTER_CONFIG.json:/app/MASTER_CONFIG.json