services:
  manager:
    container_name: manager
    build: 
      context: ../../
      dockerfile: nodes/manager/Dockerfile
    ports:
      - "5173:80"
    cpuset: "5"
    mem_limit: 2g 
    networks: 
      - ddos-shared
    
networks:
  ddos-shared:
    external: true
